language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
script:
- "./gradlew build"
before_deploy:
- export APK_PATH=$(ls app/build/outputs/apk/*-release-unsigned.apk)
- cd app
- git init
- git config user.name "$username"
- git config user.email "$useremail"
- git add .
- git commit -m "Build"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:Build-app
- cd ..
branches:
  only:
    - master
deploy:
  provider: releases
  api_key:
    secure: rhPEQwxabhFnr+52weseDHsEBA3p8037EVcMfazZeadcr4QqItjsoTOAkS4fFQDTzvJHDdZjbdAoMPG5m9prEjEf3LhfrrZTg6rdrmywcQj849EJD6u+aJR8A8oiQG64H3LrLlnmTZbdSgltFUKneleFpSUBRnJuADKPMb7pkPcFVMA7i8CruVXezy1xHvS38n98qVIwQRMhyulkOgcRMCYjXriQxuxtv32BwRILDtKdP7EIRdwvfLekA3o39B0Z/BLCRrvxRQBU/R6PcnQw++GZcjlyIdRwFx2bX1MOX5Wc4aMCYrat1Ym6RE/I4ZjwatQwhoeqBJqm8dsJSvMYQVtoq4zVW5L8bYZ8bRWvXkB0lT9JEZ0L32/YRyIZNyy2HH8m34NKVBOkPmw6b4t8OLKPGA49ELraGs6SHRdzXLlrCPvQTah+fU7EPQqoVHuyFSFHM6MOS0raHWDOCJC4LZq/XUPhIOAfPFoPmQybV45eRkVUedPoVzOJ5eeSqGobbJ8ghyPCOTwCBGl0BfWZ8Uzsgoc0LykW1jY/DStHE1kgfCWuQ9FVQ+pcMHnp7opNOGyKWVxy9J1+7A6B3tkZbHlC8vzeXsP+8xPYjoZpc7vikhifQBLPymmAblyBslchmUtHuOfi41halwi8eEEj7MYzHTGechZeBhvd0I7Q+Bg=
  file: "$APK_PATH"
  skip_cleanup: true
  on:
    repo: Ezalor/XposedInstaller
    all_branches: true
before_install:
- gem install fir-cli
after_deploy:
- fir p $APK_PATH -T ${FIR_TOKEN}

