language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository


sudo: required

script:
  - "./gradlew assembleRelease"
 
deploy:
  provider: releases
  api_key: db2baddf5e4ba5d3c36979bb33dd3dad3c58cbad
  file: app/build/outputs/apk/XposedInstaller_by_dvdandroid-release-unsigned.apk
  skip_cleanup: true
