language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
script:
- "./gradlew build"
after_script:
- cd app
- git init
- git config user.name "${username}"
- git config user.email "${useremail}"
- git add .
- git commit -m "Build"
- git push --force --quite "https://${GH_TOKEN}@${GH_REF}" master:Build-app
branches:
  only:
    - master
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TRAVIS}
  file: app/build/outputs/apk/XposedInstaller_by_dvdandroid-release-unsigned.apk
  skip_cleanup: true
  on:
    repo: Ezalor/XposedInstaller
    tags: ture
    all_branches: true
before_install:
- gem install fir-cli
after_deploy:
- fir p app/build/outputs/apk/XposedInstaller_by_dvdandroid-release-unsigned.apk -T ${FIR_TOKEN}

