language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - "./gradlew assembleRelease"
 
deploy:
  provider: releases
  api_key: 8dc93f802cf351b96a12834f707e971f27d0cd64
  file: app/build/outputs/apk/XposedInstaller_by_dvdandroid-release-unsigned.apk
  skip_cleanup: true
  on:
    tags: true
